
  CREATE TABLE "SYSTEM"."USERS" 
   (	"USERNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ENABLED" NUMBER, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


REM INSERTING into USERS
SET DEFINE OFF;
Insert into USERS (USERNAME,PASSWORD,ENABLED) values ('sam','{noop}sam',1);
Insert into USERS (USERNAME,PASSWORD,ENABLED) values ('kam','{noop}kam',1);
Insert into USERS (USERNAME,PASSWORD,ENABLED) values ('ash','{noop}ash',1);



  CREATE TABLE "SYSTEM"."AUTHORITIES" 
   (	"USERNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AUTHORITY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "AUTHORITIES_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."USERS" ("USERNAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  REM INSERTING into AUTHORITIES
SET DEFINE OFF;
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('sam','ROLE_MANAGER');
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('sam','ROLE_EMPLOYEE');
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('kam','ROLE_EMPLOYEE');
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('ash','ROLE_ADMIN');

